In [1]:
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import MaxPooling2D
from keras.layers import Conv2D, Flatten
import cv2
import pathlib
import numpy as np
from sklearn.model_selection import train_test_split
from keras.callbacks import EarlyStopping,ModelCheckpoint
from tqdm import tqdm
import pandas as pd
from keras.models import load_model
from collections import Counter
import warnings
warnings.filterwarnings('ignore')
model1=load_model('out/best_identification_model.hdf5')
model2=load_model('out/best_identification_model.hdf5')

In [2]:
class cascade:
    def __init__(self):
        self.model_list = []
    def add(self,model):
        self.model_list.append(model)
    def predict(self,array):
        liste=[]
        for model in self.model_list:
            liste2=[]
            for pred in model.predict(array):
                try:
                    liste2.append(list(pred).index(1))
                except:
                    liste2.append(None)
            liste.append(liste2)
            self.prediction=liste
        return liste
    def none(self):
        try:
            model_name=[]
            model_tag=[]
            number_of_none=[]
            number_of_not_none=[]
            i=1
            for liste in self.prediction:
                model_name.append("Model %s"%i)
                model_tag.append(str(self.model_list[i-1]))
                number_of_none.append(self.prediction[i-1].count(None))
                number_of_not_none.append(len(self.prediction[i-1])-self.prediction[i-1].count(None))
                i+=1
            self.df=pd.DataFrame({"model name":model_name,"model tag":model_tag,"number of None": number_of_none,"number of not None": number_of_not_none})
            return self.df
        except AttributeError:
            raise AttributeError("Call .predict() function before calling .none()")
    def get_value(self,i):
        liste=[]
        for k in range(len(self.prediction)):
            if self.prediction[k][i]!=None:
                liste.append(self.prediction[k][i])
        return liste
    
    def tiebreak(self,based_on="most_common",accuracy=None):
        if accuracy is None and based_on=="accuracy_model":
            raise SyntaxError("Accuracy must be a list of your model's accuracy in order")
        if based_on not in ["most_common","accuracy_model"]:
            raise SyntaxError("%s is not a valid parameter, use 'most_common or 'accuracy_model'"%based_on)

        liste=[]
        for k in range(len(self.prediction[0])):
            if based_on=="most_common":
                try:
                    liste.append(Counter(self.get_value(k)).most_common(1)[0][0])
                except:
                    liste.append(None)
            if based_on=="accuracy_model":
                liste2=[]
                for p in set(self.get_value(k)):
                    liste2.append((p,math.prod([1-accuracy[i] for i, x in enumerate(self.get_value(k)) if x == p and p!=None])))
                #liste.append(self.get_value(k)[liste2.index(min(liste2))])
                try:
                    liste.append(list(set(self.get_value(k)))[liste2.index(min(liste2))])
                except:
                    liste.append(None)
        return liste

In [3]:
def increase_contrast(img):
    clahe = cv2.createCLAHE(clipLimit=50., tileGridSize=(8,8))
    lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)  # convert from BGR to LAB color space
    l, a, b = cv2.split(lab)  # split on 3 different channels
    l2 = clahe.apply(l)  # apply CLAHE to the L-channel
    lab = cv2.merge((l2,a,b))  # merge channels
    img = cv2.cvtColor(lab, cv2.COLOR_LAB2BGR)  # convert from LAB to BGR
    return img 

def Preprocessing(image):
    matrix=[]
    image=cv2.imread(r"%s"%image)
    image=increase_contrast(cv2.cvtColor(image, cv2.COLOR_BGR2HLS))
    for k in range(len(image)-1):
        matrix.append(np.round(np.array([image[k][k],image[k][k+1],image[k+1][k],image[k+1][k+1]]).mean()))
    return matrix

In [68]:
cas= cascade()
cas.add(model1)
cas.add(model2)
A=cas.predict(X_train)
cas.none()

186/186 [==============================] - 3s 13ms/step
186/186 [==============================] - 2s 13ms/step

,model name,model tag,number of None,number of not None
0,Model 1,<keras.engine.sequential.Sequential object at ...,153,5787
1,Model 2,<keras.engine.sequential.Sequential object at ...,153,5787

In [60]:
cas.tiebreak(based_on="accuracy_model",accuracy=[0.98,0.88])==cas.tiebreak(based_on="most_common")

True

In [62]:
cas.info()

,model name,model tag,number of None,number of not None
0,Model 1,<keras.engine.sequential.Sequential object at ...,153,5787
1,Model 2,<keras.engine.sequential.Sequential object at ...,153,5787

In [63]:
A

[[348,
  168,
  473,
  386,
  145,
  261,
  271,
  260,
  120,
  36,
  276,
  378,
  248,
  173,
  335,
  121,
  21,
  38,
  176,
  42,
  355,
  357,
  351,
  19,
  46,
  442,
  45,
  308,
  295,
  232,
  238,
  173,
  461,
  25,
  59,
  341,
  131,
  109,
  330,
  1,
  210,
  155,
  425,
  290,
  97,
  395,
  176,
  251,
  99,
  187,
  239,
  469,
  212,
  262,
  7,
  173,
  None,
  65,
  141,
  153,
  255,
  142,
  330,
  321,
  305,
  490,
  None,
  50,
  411,
  129,
  392,
  402,
  265,
  365,
  132,
  259,
  283,
  33,
  2,
  123,
  223,
  49,
  262,
  462,
  155,
  47,
  184,
  163,
  72,
  383,
  204,
  474,
  67,
  123,
  394,
  189,
  86,
  377,
  6,
  100,
  273,
  128,
  14,
  215,
  499,
  405,
  119,
  24,
  301,
  303,
  13,
  85,
  34,
  329,
  494,
  413,
  396,
  453,
  181,
  484,
  67,
  409,
  412,
  None,
  430,
  248,
  316,
  180,
  256,
  141,
  85,
  328,
  177,
  441,
  225,
  86,
  489,
  447,
  346,
  141,
  242,
  406,
  276,
  418,
  215,
  440,
  354,
  98,
  311,
  65,
  366,
  4,
  59,
  192,
  322,
  203,
  186,
  383,
  399,
  258,
  463,
  56,
  463,
  303,
  224,
  None,
  130,
  None,
  205,
  28,
  124,
  195,
  325,
  None,
  51,
  341,
  116,
  274,
  332,
  431,
  384,
  None,
  249,
  3,
  None,
  348,
  44,
  220,
  306,
  195,
  232,
  457,
  185,
  89,
  99,
  428,
  21,
  144,
  444,
  75,
  111,
  116,
  80,
  19,
  16,
  201,
  455,
  359,
  392,
  482,
  27,
  223,
  485,
  368,
  8,
  144,
  438,
  73,
  491,
  34,
  312,
  103,
  190,
  112,
  238,
  74,
  98,
  387,
  443,
  308,
  372,
  360,
  60,
  86,
  255,
  471,
  408,
  81,
  414,
  218,
  102,
  100,
  456,
  48,
  454,
  235,
  479,
  226,
  468,
  146,
  None,
  155,
  None,
  39,
  436,
  96,
  11,
  128,
  207,
  136,
  110,
  452,
  99,
  364,
  330,
  401,
  56,
  148,
  367,
  383,
  380,
  241,
  473,
  295,
  470,
  114,
  162,
  14,
  339,
  395,
  41,
  150,
  73,
  58,
  280,
  193,
  241,
  318,
  213,
  19,
  424,
  129,
  353,
  424,
  398,
  None,
  434,
  422,
  1,
  431,
  239,
  137,
  94,
  194,
  90,
  466,
  371,
  124,
  252,
  156,
  221,
  426,
  284,
  58,
  368,
  290,
  44,
  218,
  263,
  291,
  304,
  216,
  476,
  459,
  87,
  473,
  418,
  1,
  311,
  358,
  489,
  195,
  474,
  130,
  468,
  155,
  257,
  5,
  283,
  None,
  487,
  200,
  480,
  236,
  167,
  106,
  412,
  157,
  359,
  164,
  341,
  7,
  257,
  406,
  124,
  241,
  117,
  288,
  305,
  391,
  481,
  375,
  63,
  138,
  35,
  251,
  215,
  31,
  419,
  377,
  197,
  230,
  280,
  152,
  135,
  272,
  44,
  295,
  62,
  300,
  44,
  120,
  76,
  260,
  411,
  451,
  15,
  147,
  384,
  235,
  276,
  454,
  99,
  340,
  177,
  449,
  39,
  410,
  110,
  21,
  23,
  46,
  357,
  16,
  327,
  364,
  189,
  145,
  157,
  154,
  None,
  491,
  252,
  115,
  174,
  256,
  361,
  266,
  133,
  None,
  143,
  269,
  437,
  474,
  388,
  399,
  101,
  108,
  231,
  1,
  452,
  29,
  450,
  113,
  180,
  169,
  317,
  85,
  None,
  187,
  192,
  488,
  316,
  316,
  483,
  61,
  105,
  216,
  134,
  67,
  399,
  56,
  415,
  296,
  321,
  317,
  463,
  392,
  364,
  None,
  321,
  321,
  0,
  155,
  234,
  112,
  48,
  52,
  301,
  460,
  35,
  2,
  87,
  3,
  278,
  87,
  91,
  87,
  156,
  372,
  386,
  145,
  214,
  5,
  362,
  255,
  444,
  218,
  93,
  208,
  282,
  58,
  415,
  413,
  272,
  334,
  134,
  351,
  164,
  401,
  463,
  327,
  109,
  473,
  474,
  233,
  481,
  319,
  396,
  62,
  353,
  39,
  286,
  472,
  24,
  25,
  206,
  198,
  294,
  275,
  322,
  344,
  301,
  223,
  20,
  478,
  191,
  139,
  174,
  421,
  97,
  327,
  365,
  256,
  238,
  465,
  475,
  431,
  137,
  284,
  27,
  216,
  488,
  179,
  96,
  297,
  373,
  381,
  412,
  250,
  20,
  406,
  294,
  66,
  140,
  390,
  349,
  160,
  184,
  101,
  None,
  126,
  362,
  104,
  444,
  430,
  49,
  134,
  26,
  436,
  189,
  12,
  394,
  153,
  24,
  37,
  496,
  400,
  283,
  57,
  95,
  136,
  349,
  148,
  414,
  None,
  54,
  261,
  158,
  368,
  86,
  385,
  117,
  478,
  139,
  424,
  114,
  423,
  261,
  None,
  310,
  340,
  None,
  135,
  305,
  31,
  259,
  151,
  302,
  35,
  67,
  114,
  139,
  174,
  460,
  10,
  8,
  338,
  None,
  252,
  242,
  40,
  94,
  301,
  126,
  11,
  216,
  166,
  236,
  151,
  62,
  333,
  418,
  91,
  447,
  193,
  159,
  128,
  305,
  370,
  308,
  98,
  129,
  471,
  12,
  31,
  None,
  91,
  451,
  10,
  463,
  50,
  402,
  161,
  34,
  187,
  112,
  191,
  452,
  354,
  164,
  373,
  108,
  254,
  20,
  116,
  335,
  37,
  118,
  390,
  99,
  118,
  379,
  313,
  326,
  372,
  122,
  393,
  342,
  292,
  240,
  127,
  34,
  382,
  143,
  54,
  296,
  83,
  371,
  281,
  331,
  492,
  123,
  49,
  173,
  None,
  376,
  133,
  440,
  236,
  None,
  82,
  183,
  156,
  380,
  114,
  156,
  17,
  401,
  353,
  35,
  482,
  117,
  470,
  92,
  439,
  9,
  256,
  485,
  188,
  212,
  169,
  97,
  314,
  203,
  265,
  245,
  382,
  382,
  300,
  328,
  178,
  479,
  122,
  36,
  482,
  88,
  232,
  8,
  296,
  2,
  186,
  74,
  255,
  135,
  62,
  196,
  48,
  161,
  415,
  195,
  467,
  434,
  320,
  426,
  495,
  193,
  112,
  286,
  386,
  489,
  80,
  14,
  232,
  125,
  337,
  178,
  485,
  290,
  378,
  440,
  457,
  155,
  7,
  234,
  284,
  200,
  205,
  None,
  5,
  302,
  125,
  290,
  428,
  389,
  63,
  24,
  362,
  37,
  39,
  286,
  None,
  36,
  265,
  124,
  295,
  312,
  48,
  181,
  20,
  349,
  30,
  380,
  241,
  134,
  237,
  315,
  350,
  458,
  103,
  197,
  355,
  372,
  365,
  46,
  180,
  497,
  496,
  395,
  487,
  356,
  163,
  355,
  274,
  465,
  12,
  389,
  394,
  396,
  439,
  None,
  291,
  485,
  307,
  385,
  None,
  146,
  439,
  379,
  62,
  481,
  127,
  86,
  457,
  323,
  221,
  425,
  129,
  40,
  364,
  281,
  460,
  39,
  441,
  192,
  466,
  67,
  472,
  406,
  74,
  447,
  208,
  473,
  360,
  29,
  20,
  15,
  198,
  98,
  175,
  356,
  18,
  179,
  480,
  107,
  494,
  404,
  328,
  455,
  233,
  265,
  158,
  419,
  185,
  319,
  265,
  24,
  226,
  45,
  354,
  460,
  130,
  89,
  None,
  203,
  110,
  421,
  247,
  267,
  222,
  201,
  None,
  425,
  254,
  236,
  309,
  278,
  266,
  405,
  None,
  None,
  483,
  95,
  386,
  77,
  None,
  185,
  394,
  270,
  289,
  420,
  390,
  317,
  341,
  450,
  42,
  125,
  138,
  22,
  176,
  430,
  375,
  123,
  358,
  58,
  319,
  299,
  8,
  420,
  416,
  443,
  397,
  436,
  320,
  79,
  197,
  324,
  319,
  220,
  268,
  410,
  242,
  90,
  294,
  295,
  386,
  118,
  230,
  148,
  373,
  157,
  471,
  470,
  34,
  101,
  403,
  478,
  47,
  39,
  486,
  11,
  101,
  441,
  91,
  178,
  50,
  315,
  214,
  41,
  211,
  373,
  435,
  205,
  60,
  90,
  85,
  113,
  271,
  234,
  283,
  400,
  402,
  241,
  283,
  246,
  395,
  28,
  438,
  163,
  296,
  ...],
 [348,
  168,
  473,
  386,
  145,
  261,
  271,
  260,
  120,
  36,
  276,
  378,
  248,
  173,
  335,
  121,
  21,
  38,
  176,
  42,
  355,
  357,
  351,
  19,
  46,
  442,
  45,
  308,
  295,
  232,
  238,
  173,
  461,
  25,
  59,
  341,
  131,
  109,
  330,
  1,
  210,
  155,
  425,
  290,
  97,
  395,
  176,
  251,
  99,
  187,
  239,
  469,
  212,
  262,
  7,
  173,
  None,
  65,
  141,
  153,
  255,
  142,
  330,
  321,
  305,
  490,
  None,
  50,
  411,
  129,
  392,
  402,
  265,
  365,
  132,
  259,
  283,
  33,
  2,
  123,
  223,
  49,
  262,
  462,
  155,
  47,
  184,
  163,
  72,
  383,
  204,
  474,
  67,
  123,
  394,
  189,
  86,
  377,
  6,
  100,
  273,
  128,
  14,
  215,
  499,
  405,
  119,
  24,
  301,
  303,
  13,
  85,
  34,
  329,
  494,
  413,
  396,
  453,
  181,
  484,
  67,
  409,
  412,
  None,
  430,
  248,
  316,
  180,
  256,
  141,
  85,
  328,
  177,
  441,
  225,
  86,
  489,
  447,
  346,
  141,
  242,
  406,
  276,
  418,
  215,
  440,
  354,
  98,
  311,
  65,
  366,
  4,
  59,
  192,
  322,
  203,
  186,
  383,
  399,
  258,
  463,
  56,
  463,
  303,
  224,
  None,
  130,
  None,
  205,
  28,
  124,
  195,
  325,
  None,
  51,
  341,
  116,
  274,
  332,
  431,
  384,
  None,
  249,
  3,
  None,
  348,
  44,
  220,
  306,
  195,
  232,
  457,
  185,
  89,
  99,
  428,
  21,
  144,
  444,
  75,
  111,
  116,
  80,
  19,
  16,
  201,
  455,
  359,
  392,
  482,
  27,
  223,
  485,
  368,
  8,
  144,
  438,
  73,
  491,
  34,
  312,
  103,
  190,
  112,
  238,
  74,
  98,
  387,
  443,
  308,
  372,
  360,
  60,
  86,
  255,
  471,
  408,
  81,
  414,
  218,
  102,
  100,
  456,
  48,
  454,
  235,
  479,
  226,
  468,
  146,
  None,
  155,
  None,
  39,
  436,
  96,
  11,
  128,
  207,
  136,
  110,
  452,
  99,
  364,
  330,
  401,
  56,
  148,
  367,
  383,
  380,
  241,
  473,
  295,
  470,
  114,
  162,
  14,
  339,
  395,
  41,
  150,
  73,
  58,
  280,
  193,
  241,
  318,
  213,
  19,
  424,
  129,
  353,
  424,
  398,
  None,
  434,
  422,
  1,
  431,
  239,
  137,
  94,
  194,
  90,
  466,
  371,
  124,
  252,
  156,
  221,
  426,
  284,
  58,
  368,
  290,
  44,
  218,
  263,
  291,
  304,
  216,
  476,
  459,
  87,
  473,
  418,
  1,
  311,
  358,
  489,
  195,
  474,
  130,
  468,
  155,
  257,
  5,
  283,
  None,
  487,
  200,
  480,
  236,
  167,
  106,
  412,
  157,
  359,
  164,
  341,
  7,
  257,
  406,
  124,
  241,
  117,
  288,
  305,
  391,
  481,
  375,
  63,
  138,
  35,
  251,
  215,
  31,
  419,
  377,
  197,
  230,
  280,
  152,
  135,
  272,
  44,
  295,
  62,
  300,
  44,
  120,
  76,
  260,
  411,
  451,
  15,
  147,
  384,
  235,
  276,
  454,
  99,
  340,
  177,
  449,
  39,
  410,
  110,
  21,
  23,
  46,
  357,
  16,
  327,
  364,
  189,
  145,
  157,
  154,
  None,
  491,
  252,
  115,
  174,
  256,
  361,
  266,
  133,
  None,
  143,
  269,
  437,
  474,
  388,
  399,
  101,
  108,
  231,
  1,
  452,
  29,
  450,
  113,
  180,
  169,
  317,
  85,
  None,
  187,
  192,
  488,
  316,
  316,
  483,
  61,
  105,
  216,
  134,
  67,
  399,
  56,
  415,
  296,
  321,
  317,
  463,
  392,
  364,
  None,
  321,
  321,
  0,
  155,
  234,
  112,
  48,
  52,
  301,
  460,
  35,
  2,
  87,
  3,
  278,
  87,
  91,
  87,
  156,
  372,
  386,
  145,
  214,
  5,
  362,
  255,
  444,
  218,
  93,
  208,
  282,
  58,
  415,
  413,
  272,
  334,
  134,
  351,
  164,
  401,
  463,
  327,
  109,
  473,
  474,
  233,
  481,
  319,
  396,
  62,
  353,
  39,
  286,
  472,
  24,
  25,
  206,
  198,
  294,
  275,
  322,
  344,
  301,
  223,
  20,
  478,
  191,
  139,
  174,
  421,
  97,
  327,
  365,
  256,
  238,
  465,
  475,
  431,
  137,
  284,
  27,
  216,
  488,
  179,
  96,
  297,
  373,
  381,
  412,
  250,
  20,
  406,
  294,
  66,
  140,
  390,
  349,
  160,
  184,
  101,
  None,
  126,
  362,
  104,
  444,
  430,
  49,
  134,
  26,
  436,
  189,
  12,
  394,
  153,
  24,
  37,
  496,
  400,
  283,
  57,
  95,
  136,
  349,
  148,
  414,
  None,
  54,
  261,
  158,
  368,
  86,
  385,
  117,
  478,
  139,
  424,
  114,
  423,
  261,
  None,
  310,
  340,
  None,
  135,
  305,
  31,
  259,
  151,
  302,
  35,
  67,
  114,
  139,
  174,
  460,
  10,
  8,
  338,
  None,
  252,
  242,
  40,
  94,
  301,
  126,
  11,
  216,
  166,
  236,
  151,
  62,
  333,
  418,
  91,
  447,
  193,
  159,
  128,
  305,
  370,
  308,
  98,
  129,
  471,
  12,
  31,
  None,
  91,
  451,
  10,
  463,
  50,
  402,
  161,
  34,
  187,
  112,
  191,
  452,
  354,
  164,
  373,
  108,
  254,
  20,
  116,
  335,
  37,
  118,
  390,
  99,
  118,
  379,
  313,
  326,
  372,
  122,
  393,
  342,
  292,
  240,
  127,
  34,
  382,
  143,
  54,
  296,
  83,
  371,
  281,
  331,
  492,
  123,
  49,
  173,
  None,
  376,
  133,
  440,
  236,
  None,
  82,
  183,
  156,
  380,
  114,
  156,
  17,
  401,
  353,
  35,
  482,
  117,
  470,
  92,
  439,
  9,
  256,
  485,
  188,
  212,
  169,
  97,
  314,
  203,
  265,
  245,
  382,
  382,
  300,
  328,
  178,
  479,
  122,
  36,
  482,
  88,
  232,
  8,
  296,
  2,
  186,
  74,
  255,
  135,
  62,
  196,
  48,
  161,
  415,
  195,
  467,
  434,
  320,
  426,
  495,
  193,
  112,
  286,
  386,
  489,
  80,
  14,
  232,
  125,
  337,
  178,
  485,
  290,
  378,
  440,
  457,
  155,
  7,
  234,
  284,
  200,
  205,
  None,
  5,
  302,
  125,
  290,
  428,
  389,
  63,
  24,
  362,
  37,
  39,
  286,
  None,
  36,
  265,
  124,
  295,
  312,
  48,
  181,
  20,
  349,
  30,
  380,
  241,
  134,
  237,
  315,
  350,
  458,
  103,
  197,
  355,
  372,
  365,
  46,
  180,
  497,
  496,
  395,
  487,
  356,
  163,
  355,
  274,
  465,
  12,
  389,
  394,
  396,
  439,
  None,
  291,
  485,
  307,
  385,
  None,
  146,
  439,
  379,
  62,
  481,
  127,
  86,
  457,
  323,
  221,
  425,
  129,
  40,
  364,
  281,
  460,
  39,
  441,
  192,
  466,
  67,
  472,
  406,
  74,
  447,
  208,
  473,
  360,
  29,
  20,
  15,
  198,
  98,
  175,
  356,
  18,
  179,
  480,
  107,
  494,
  404,
  328,
  455,
  233,
  265,
  158,
  419,
  185,
  319,
  265,
  24,
  226,
  45,
  354,
  460,
  130,
  89,
  None,
  203,
  110,
  421,
  247,
  267,
  222,
  201,
  None,
  425,
  254,
  236,
  309,
  278,
  266,
  405,
  None,
  None,
  483,
  95,
  386,
  77,
  None,
  185,
  394,
  270,
  289,
  420,
  390,
  317,
  341,
  450,
  42,
  125,
  138,
  22,
  176,
  430,
  375,
  123,
  358,
  58,
  319,
  299,
  8,
  420,
  416,
  443,
  397,
  436,
  320,
  79,
  197,
  324,
  319,
  220,
  268,
  410,
  242,
  90,
  294,
  295,
  386,
  118,
  230,
  148,
  373,
  157,
  471,
  470,
  34,
  101,
  403,
  478,
  47,
  39,
  486,
  11,
  101,
  441,
  91,
  178,
  50,
  315,
  214,
  41,
  211,
  373,
  435,
  205,
  60,
  90,
  85,
  113,
  271,
  234,
  283,
  400,
  402,
  241,
  283,
  246,
  395,
  28,
  438,
  163,
  296,
  ...]]

In [81]:
(1-0.8)*(1-0.3)*(1-0.5)

0.06999999999999998

In [83]:
(1-0.9)*(1-0.92)

0.007999999999999995

In [85]:
a.index(set(a)[0])

TypeError: 'set' object is not subscriptable

In [124]:
import math
for k in set(a):
    print(k,math.prod([1-b[i] for i, x in enumerate(a) if x == k and k!=None]))

2 0.007999999999999995
100 0.06999999999999998
30 0.010000000000000009

In [120]:
cas.nan()['number of None']/len(X_train)

0    0.025758
1    0.025758
Name: number of None, dtype: float64

In [122]:
cas.nan()

,model name,model tag,number of None,number of not None
0,Model 1,<keras.engine.sequential.Sequential object at ...,153,5787
1,Model 2,<keras.engine.sequential.Sequential object at ...,153,5787

In [33]:
a=[0.5,0.8]

0